board/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from user_auth.views import custom_login
from boardapp.views import IndexView, show_notices, NoticeList

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^board/$', show_notices, name='board'),

    # User Related urls
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'board'}, name='auth_logout'),
    url(r'^users/login/$', custom_login, name='auth_login'),

    url(r'^register/complete/$', RedirectView.as_view(pattern_name='board'), name='registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls', namespace='users')),

    # Social Auth Related urls
    url('^social/', include('social.apps.django_app.urls', namespace='social')),

    url(r'^admin/', admin.site.urls),
]

boardapp/models.py
from __future__ import unicode_literals

from django.db import models

from mptt.models import MPTTModel, TreeForeignKey

class BaseNotice(MPTTModel):
    """Base class for Messages and Comments"""
    content = models.TextField(blank=False, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True, default=None)

    class Meta:
        abstract = True


class Notice(BaseNotice):
    """class for root messages (in top of tree)"""

    user = models.ForeignKey('auth.User', null=True, blank=False, default=None)
    def save(self, *args, **kwargs):
        if self.parent is not None:
            try:
                self.insert_at(self.parent, position='last-child', save=False)
            except ValueError:
                self.move_to(self.parent, position='last-child')
        super(Notice, self).save(*args, **kwargs)

    def __unicode__(self):
        return u"Notice #%s, time posting: %s" % (self.id, self.created)

    class MPTTMeta:
        order_insertion_by = ['-created']

boardapp/views.py
from django.shortcuts import render
from django import forms
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.functional import cached_property

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Div, Fieldset, HTML, ButtonHolder, MultiField, Hidden
from crispy_forms.bootstrap import FormActions, PrependedText, AppendedText, FieldWithButtons, StrictButton

from .models import Notice


class IndexView(TemplateView):
    """ view for checking: if user authenticarted then redirect him to 'board' page
        else show 'index' page
    """

    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('board'))
        return super(IndexView, self).dispatch(request, *args, **kwargs)


class BaseNoticeForm(forms.ModelForm):
    """base class for add/edit form"""
    class Meta:
        model = Notice
        fields = ['content']

    def __init__(self, *args, **kwargs):
        super(BaseNoticeForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        # set form tag attributes
        self.helper.form_action = reverse('board')
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'

        # set form field properties
        self.helper.help_text_inline = True
        self.helper.html5_required = True


class NoticeForm(BaseNoticeForm):
    """for add message"""

    def __init__(self, *args, **kwargs):
        super(NoticeForm, self).__init__(*args, **kwargs)

        self.helper.layout = Layout(
            'content',
            FormActions(
                Submit('add_button', 'Add message', css_class="btn btn-primary btn-lg"),
            ),
        )

        # set form field properties
        self.helper.field_class = 'col-sm-12'

    content =forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': "Write your message here!",
                                     'rows': 3}),
        label=False
    )


class CorrectNoticeForm(BaseNoticeForm):
    """class for correct message"""
    def __init__(self, *args, **kwargs):
        super(CorrectNoticeForm, self).__init__(*args, **kwargs)

        self.helper.layout = Layout(
            Div(HTML("""
                    <input type="hidden" value="{{ node.id }}" name="id-node">
                """)),
            'content',
            FormActions(Submit('correct_message', 'Correct message'),
                        Submit('cancel_correct_message', 'Cancel', css_class="btn btn-danger"),
                       ),

        )
        # set form field properties
        self.helper.field_class = 'col-sm-12'

    content = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': "Write your corrected comment here!",
                                     'rows': 2, 'id': "id_content_correct",
                                     },
                              ),
        label=False
    )


class CommentForm(BaseNoticeForm):
    """ form for comment messages """

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        self.helper.layout = Layout(
            Div(HTML("""
                    <input type="hidden" value="{{ node.id }}" name="id-node">
                """)),
            FieldWithButtons('content', Submit('add_comment', 'Add comment')),

        )

        # set form field properties
        self.helper.field_class = 'col-sm-offset-1 col-sm-10'

    content = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': "Write your comment here!",
                                     'rows': 1, 'id': "id_content_comment",
                                     },
                              ),
        label=False
    )


def index_in_general_qs(qs, index, root_id):
    while qs[index].id != root_id:
            index += 1
    return index

def paginator(objects, size, request, context, var_name='objects_list'):
    """
        Paginate objects provided by view.

        THis function takes:
            * list of elements;
            * number of objects per page;
            * request object to get url paramerers from;
            * context to set new variables into;
            * var_name = variable name for list of objects.

        It returns updated context object. It returns objects grouped by root instances that include their
        comment-messages. As result on page we can see more messages than size. Besause instance can have comments!
    """

    # apply pagination
    paginator = Paginator(objects, size)

    # try to get page number fron request
    page = request.GET.get('page', '1')
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer, deliver first page
        object_list = paginator.page(1)
    except EmptyPage:
        # if page is out of range (e.g. 9999), deliver last page of results
        object_list = paginator.page(paginator.num_pages)


    bottom_root_id = object_list[0].id

    all_messages = Notice.objects.all()
    # i, j - indexes in general queryset Notice.objects.all()


    i = index_in_general_qs(all_messages,0,bottom_root_id)

    j = i
    if object_list.has_next():
        next_object_list = paginator.page(object_list.next_page_number())
        top_root_id = next_object_list[0].id
        j = index_in_general_qs(all_messages,j,top_root_id)
    else:
        j = len(all_messages)
    custom_obj_list = all_messages[i:j]


    # set variable into context
    context[var_name] = custom_obj_list
    context['num_current'] = object_list.number
    context['num_pages'] = paginator.num_pages

    return context


def show_notices(request):
    form, form_comment, form_correct = None, None, None

    if request.method == 'POST':

        # if we pushed 'Add message' ( added new message )
        if request.POST.get('add_button'):
            form = NoticeForm(request.POST)
            form_comment = CommentForm()
            form_correct = CorrectNoticeForm()

            if form.is_valid():
                try:
                    notice = form.save(commit=False)
                    notice.user = request.user
                    notice.save()
                except Exception as e:
                    messages.error(request, 'Error during adding message!' + str(e))
                else:
                    messages.success(request, 'Message was added successful!')
                return HttpResponseRedirect(reverse('board'))
            else:
                messages.info(request, 'Validation errors!')

        # if was pushed 'Add comment' button
        elif request.POST.get('add_comment'):
            form = NoticeForm()
            form_comment = CommentForm(request.POST)
            form_correct = CorrectNoticeForm()

            if form_comment.is_valid():
                try:
                    notice = form_comment.save(commit=False)
                    notice.user = request.user
                    notice.parent = Notice.objects.get(pk=request.POST.get('id-node'))
                    notice.save()
                except Exception as e:
                    messages.error(request, 'Error during adding message!' + str(e))
                else:
                    messages.success(request, 'Comment was added successful!')
                return HttpResponseRedirect(reverse('board'))
            else:
                messages.info(request, 'Validation errors!')

        # if we pushed 'Correct message' button
        elif request.POST.get('correct_message'):
            form = NoticeForm()
            form_comment = CommentForm()
            form_correct = CorrectNoticeForm(request.POST)

            if form_correct.is_valid():
                try:
                    notice = Notice.objects.get(pk=request.POST.get('id-node'))
                    notice.content = request.POST.get('content')
                    notice.save()
                except Exception as e:
                    messages.error(request, 'Error during adding message!' + str(e))
                else:
                    messages.success(request, 'Message was corrected successful!')
                return HttpResponseRedirect(reverse('board'))
            else:
                messages.info(request, 'Validation errors!')

        # if we pushed 'Cancel' button
        elif request.POST.get('cancel_correct_message'):
            messages.info(request, 'Canceled correct message!')
            return HttpResponseRedirect(reverse('board'))
    else:
        form = NoticeForm()
        form_comment = CommentForm()
        form_correct = CorrectNoticeForm()

    context = {
        'form': form,
        'form_comment': form_comment,
        'form_correct': form_correct,
        }

    paginate_by = 5
    context = paginator(Notice.objects.root_nodes(), paginate_by, request, context,
        var_name='notices')

    return render(request, "board.html", context)


class NoticeList(ListView):
    model = Notice
    queryset = Notice.objects.all()
    template_name = 'board.html'
    context_object_name = 'notices'

boardapp/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8"/>
		<title>Board of messagess of users {% block meta_title %}{% endblock meta_title %}</title>
		<meta name="description"
			  value='App for make recordings on board' >
		<meta name="viewport" content="width=device-width, initial-scale=1" >

		<!-- Style Section -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css" >
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />

	</head>

	<body>
        <!-- Start Header -->
			<div id="header" class="bg-info" >
                <div class="row">
                    <!-- Logo -->
                    <div class="col-xs-offset-3 col-xs-6">
                        <h1 class="text-center">Board of messages!</h1>
                    </div>

                    <div class="col-xs-3 text-right" id="user-toolbar">
                        {% if user.is_authenticated %}
                            <p>{{ user.get_full_name|default:user.username }}</p>
							<p> {{ user.email }}</p>

						{% comment %}
							<!--<p><a href="{% url 'users:auth_logout' %}" class="auth-link">Logout</a></p>-->
						<!-- {% else %}-->
							<!--<p><a href="{% url 'users:auth_login' %}" class="auth-link">Login</a></p>-->
							<!--<p><a href="{% url 'users:registration_register' %}" class="auth-link">Register</a></p>-->
						{% endcomment %}

						{% endif %}
                    </div>
                </div>

            </div>

		<!-- Start Container -->
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<!-- Status Message -->
					{% block status_message %}

					{% if messages %}
						{% for message in messages %}
							<div class="alert alert-warning">
								{{ message }}
							</div>
						{% endfor %}
					{% endif %}

					{% endblock %}
				</div>
			</div>

            <div class="row">
				<div class="col-xs-4"><h2>{% block title %}{% endblock title %}</h2></div>
			</div>

			<!-- Start Content -->
			<div class="row" id="legend">
				<div class="col-xs-12">
                    {% block content %}{% endblock content %}
				</div>
			</div>
			<!-- End Content -->

			<!-- Start Footer -->
			<div class="row" id="footer">
                <hr class="divider">
				<div class="col-xs-12">
					&copy; 2016 Board of messages
				</div>
			</div>
			<!-- End Footer -->

		</div>
		<!-- End Container -->

		<!-- JavaScript Section -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js" type="text/javascript"></script>
        <script src="https://www.google.com/jsapi" type="text/javascript"></script>
		<script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js" type="text/javascript"></script>

		<script src="{% static 'js/endless_scroll.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
	</body>

</html>

boardapp/templates/board.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load mptt_tags %}
{% load crispy_forms_tags %}

{% block meta_title %} - Board for messages{% endblock meta_title %}

{% block content %}

<input type="hidden" data-num-pages="{{ num_pages }}" data-page="{{ num_current }}" id = "load_more">

<div class="text-center" id="sub-header">
{% if user.is_authenticated %}
    {% crispy form %}
{% else %}

    {% url 'board' as board_url  %}
    <span class="lead">For adding messages or comments, please:
        <a href="{% url 'index' %}">
            Log In!
        </a>
    </span>

{% endif %}
</div>

<ul class="list-group" id="notice_list">
    {% recursetree notices %}
        <li class="list-group-item lead">
            <span>
                <!--msg # {{ node.id }}-->
                ({{ node.created|date:"Y-M-d H:i:s" }})
                {{ node.user.get_full_name|default:node.user }}:
            </span>
            <p class="content">{{ node.content }}</p>
            <div class="content-correct">
                {% crispy form_correct %}
            </div>

            {% if user.is_authenticated %}
                <div id="buttons-comment-form">
                    <button type="button" class="addcomment btn btn-link" data-comment-id="{{ node.id }}">
                        Add comment
                    </button>
                    {% if user == node.user %}/
                    <button type="button" class="correct_msg btn btn-link" href="#">Correct message</button>
                        <!--{% if node.updated == node.created %}Updated {{ node.updated|date:"Y-M-d H:i:s" }}{% endif %}-->
                    {% endif %}
                    <div class="comment" id="comment_to{{ node.id }}">
                        {% crispy form_comment %}
                    </div>

                </div>
            {% endif %}

            {% if not node.is_leaf_node %}
            <ul class="children">
                <p>Comments:</p>
                {{ children }}
            </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>

<p class="text-center lead" id="loading">
    loading ...
	<img src="{% static 'img/ajax-loader.gif' %}" alt="Loading…" />
</p>

{% endblock content %}

boardapp/templates/index.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block meta_title %} - LogIn from facebook{% endblock meta_title %}

{% block content %}
<div class="text-center" id="buttons-ch">
    {% url 'board' as board_url  %}

    <a href="{% url 'social:begin' 'facebook' %}?next={{ board_url }}">
        <img src="{% static 'img/facebook3.png' %}" >
    </a>

    <div id="or">
        or
    </div>

    <a href="{% url 'board' %}">
        <button type="button" class="btn btn-default btn-lg">
        Enter without authenticating
        </button>
    </a>

</div>
{% endblock content %}